### ISSUE TITLE
License and pyproject.toml

### ISSUE THREAD

**Issue by joshuamegnauth54** [riverscuomo/new-albums#22]
# License
I noticed that your repository doesn't have a `LICENSE` file. An unlicensed repository on GitHub [defaults to all rights reserved](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). In other words, your code is legally neither open source nor free.

I'm assuming that you _don't_ want this, so you should pick a license from [Choose a License](https://choosealicense.com/). 😸 You only need to copy the license text to a file called `LICENSE` in your project's root directory. There are several licenses you may use, but you don't have to overthink your choice. The two major philosophies are **permissive**, such as the [MIT](https://choosealicense.com/licenses/mit/) license; and **copyleft**, such as the [GNU General Public License](https://choosealicense.com/licenses/gpl-3.0/). 

_Choose a License_ is pretty clear, but I can try to clarify anything if you have questions. **You should also add a license to any other repositories you own even if they're private.**

# pyproject.toml
`setup.cfg` and `requirements.txt` are part of the older method for distributing Python packages and `venv` is the older way of managing virtual environments. Over the years, Python developers created a passel of competing tools to ease dependency management, distribution, and virtual environments. Wading through all of these different tools is not only difficult but makes the ecosystem feel intractable, especially considering that these tools solve the same problems in different ways.

The Python Software Foundation (i.e., the nonprofit managing Python as a language) [consolidated](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) these different formats into `pyproject.toml`. `pyproject.toml` is similar to Rust's [cargo.toml](https://doc.rust-lang.org/cargo/reference/manifest.html), npm (JavaScript)'s [package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json), Ruby's [gemfile](https://bundler.io/guides/gemfile.html), and others. [Poetry](https://python-poetry.org/) is a tool that leverages the full power of `pyproject.toml` to make dependency management and environments much neater and easier as well.

* [Simple](https://python.plainenglish.io/poetry-a-better-version-of-python-pipenv-561611a029d1) `poetry` guide and explanation.
* A [more detailed](https://realpython.com/dependency-management-python-poetry/) explanation.

You don't have to switch over to a modern tool like `poetry` right away, but it's worth knowing that it exists for the future. Here's an example `pyproject.toml` for your repository created via `poetry`. (You totally need to add a license though.)

```toml
[tool.poetry]
name = "new-albums"
version = "0.1.0"
description = "A python script to update a Spotify playlist every day with all the songs from any significant new albums."
keywords = ["spotify", "scrape", "net"]
authors = ["Rivers Cuomo"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/riverscuomo/new-albums"

[tool.poetry.dependencies]
python = "^3.8"
argparse = "^1.4.0"
pycountry = "^22.3.5"
python_dateutil = "^2.8.2"
python-decouple = "^3.6"
rich = "^11.2.0"
spotipy = "2.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
